# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    database_path: '%kernel.root_dir%/reviewDB.db'

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
